// streaming-prototype/js/types/globals.d.ts
//
// Ambient declarations for the IIFE globals exposed by classic <script> tags
// in index.html. These do not change runtime behavior — they teach TypeScript
// what each global looks like so per-file @ts-check produces useful errors
// rather than noise.
//
// --- Session 4 update ---
// Data-shape types (Show, Channel, City, etc.) are now derived via z.infer from
// the zod schemas in ../schemas/. This eliminates dual maintenance: add a field
// to a schema file and the type here updates automatically. The zod schemas are
// the single source of truth for JSON-facing shapes.
//
// Code-facing interface types (IIFE globals, ScreenModule contract, KeyAction,
// FocusZone, etc.) remain as-is — there's no zod schema for these.
//
// --- Runtime validation decision (Session 4, Approach A) ---
// Runtime validation of fetched JSON is SKIPPED. The Node CI validator
// (tools/validate-data.js) is the primary safety net — it runs before merge
// and catches all shape drift. If browser-side runtime validation is ever
// needed (Approach B: zod via UMD script tag), the loader boundaries are:
//   • js/data-store.js  → init()            validates catalog.json, lander-config.json,
//                                            version.json, geo-state.json
//   • js/data-store.js  → getSeriesData()   validates each data/series/*.json on fetch
//   • js/welcome-screen.js                  validates device profile JSON on fetch
//   • js/screens/epg/data-model.js → init() validates epg-mock.json on fetch

import type { z } from 'zod';
import type {
  ShowSchema,
  ChannelSchema,
  CitySchema,
  CollectionSchema,
  CatalogSchema,
} from '../schemas/catalog';
import type { RailSchema, LanderConfigSchema } from '../schemas/lander-config';
import type { EpisodeSchema, SeasonSchema, ExtraSchema, SeriesDataSchema } from '../schemas/series';
import type { VersionSchema } from '../schemas/version';
import type { GeoStateSchema } from '../schemas/geo-state';
import type { EpgGenreSchema, EpgChannelSchema } from '../schemas/epg';

declare global {

  // =========================================================================
  // Data shapes — derived from zod schemas (zod is source of truth)
  // To change a shape: update the schema file, not this file.
  // =========================================================================

  /** Show entry from catalog.json */
  type Show = z.infer<typeof ShowSchema>;

  /** Channel entry in catalog.json (live TV channels per city) */
  type Channel = z.infer<typeof ChannelSchema>;

  type City = z.infer<typeof CitySchema>;
  type Collection = z.infer<typeof CollectionSchema>;
  type Catalog = z.infer<typeof CatalogSchema>;

  /**
   * Discriminated union on `type`. Derived from LanderConfigSchema.
   * To add a new rail type: add it to lander-config.js schema.
   */
  type Rail = z.infer<typeof RailSchema>;
  type LanderConfig = z.infer<typeof LanderConfigSchema>;

  type Episode = z.infer<typeof EpisodeSchema>;
  type Season = z.infer<typeof SeasonSchema>;
  type Extra = z.infer<typeof ExtraSchema>;
  type SeriesData = z.infer<typeof SeriesDataSchema>;

  type VersionInfo = z.infer<typeof VersionSchema>;
  type GeoState = z.infer<typeof GeoStateSchema>;

  // =========================================================================
  // EPG-specific types (distinct from catalog types)
  // =========================================================================

  /** Genre entry from epg-mock.json — different from catalog genres (which are plain strings) */
  type EpgGenre = z.infer<typeof EpgGenreSchema>;

  /** EPG channel from epg-mock.json — distinct shape from the catalog Channel type */
  type EpgChannel = z.infer<typeof EpgChannelSchema>;

  /**
   * Program — runtime-generated by EPGDataModel._generatePrograms(), not directly
   * from the JSON files (which store ProgramSlots, not resolved Programs).
   * Kept as an inline type because there's no JSON schema for this shape.
   */
  type Program = {
    id: string;
    channelId: string;
    title: string;
    description: string;
    rating: string;
    startTime: number;
    endTime: number;
  };

  // =========================================================================
  // IIFE singletons
  // =========================================================================
  // Using `var` (not `const`) so TypeScript doesn't flag a re-declaration conflict
  // with the IIFE `const DataStore = (function() {...})()` assignments in the
  // classic script files. `var` declarations are re-declarable at global scope.

  var DataStore: {
    init(): Promise<void>;
    getVersion(): VersionInfo;
    getShow(id: string): Show | null;
    getChannel(id: string): Channel | null;
    getCity(id: string): City | null;
    getCollection(id: string): Collection | null;
    getGeoState(): GeoState | null;
    getDetectedCity(): City | null;
    getFeaturedItems(): Array<(Show | City | Collection) & { _type: 'show' | 'city' | 'collection' }>;
    getContinueWatching(): unknown[];
    getAllShows(): Show[];
    getAllChannels(): Channel[];
    getAllCities(): City[];
    getGenres(): string[];
    getTopFlix(): Show[];
    getMyMix(): Show[];
    getSeriesData(showId: string): Promise<SeriesData | null>;
    getLanderConfig(): LanderConfig;
  };

  var App: {
    init(): Promise<void>;
    navigate(screenId: string, params?: object, replace?: boolean): Promise<void>;
    back(): boolean;
    registerScreen(module: ScreenModule): void;
  };

  type KeyAction = 'UP' | 'DOWN' | 'LEFT' | 'RIGHT' | 'OK' | 'BACK' | 'PLAYPAUSE';

  type FocusZone = {
    focus(index: number): boolean;
    blur(): void;
    move(dir: 'LEFT' | 'RIGHT'): boolean;
    select(): void;
    getIndex(): number;
    getItem(): unknown;
    getItems(): unknown[];
    setItems(items: unknown[]): void;
  };

  var FocusEngine: {
    init(): void;
    enable(): void;
    disable(): void;
    setHandler(handler: (action: KeyAction, event: KeyboardEvent) => void): void;
    clearHandler(): void;
    createZone(items: unknown[], options?: {
      startIndex?: number;
      onFocus?: (index: number, item: unknown) => void;
      onBlur?: (index: number, item: unknown) => void;
      onSelect?: (index: number, item: unknown) => void;
      wrapAround?: boolean;
    }): FocusZone;
  };

  var ScaleEngine: {
    init(options?: { maxScale?: number }): void;
    destroy(): void;
    getScale(): number;
    /** Force a specific viewport size (device simulation). Pass null to restore. */
    setViewport(width: number | null, height: number | null): void;
  };

  type ScreenModule = {
    id: string;
    init(container: HTMLElement, params?: object): Promise<void> | void;
    onFocus?: () => void;
    onBlur?: () => void;
    destroy?: () => void;
    _params?: object;
  };

  var LanderScreen: ScreenModule;
  var SeriesPDPScreen: ScreenModule;
  var PlayerScreen: ScreenModule;
  var EPGScreen: ScreenModule;

  // =========================================================================
  // analytics.js globals (set as window properties by the ES module)
  // =========================================================================

  function trackEvent(name: string, params?: Record<string, unknown>): void;
  function initSession(participantId: string, deviceProfile: string): void;
  function endSession(): void;

  // Backward-compat shim exposed by analytics.js for legacy callers in app.js
  // and scale.js. Not a primary API — use trackEvent() for new code.
  var Analytics: {
    track(eventName: string, params?: Record<string, unknown>): void;
    isFirstVisit(): boolean;
    getParticipantId(): string | null;
    setParticipantId(id: string): void;
    getSessionSummary(): { durationMs: number; screensVisited: string[]; totalEvents: number; deepestScreen?: string; totalSelections?: number; totalFocusChanges?: number };
    /** Returns raw stored events. Legacy path — Firebase transport returns []. Typed as any[] for property access in feedback.js. */
    getEvents(): any[];
    clearEvents(): void;
    readonly sessionId: string;
    /** Generates a random opaque participant code. Used by feedback.js participant-prompt flow. */
    generateNewParticipantId(): string;
    /** Returns the active device profile from sessionStorage. */
    getDeviceType(): string;
  };

  // =========================================================================
  // Other IIFE components
  // =========================================================================

  var EPGDataModel: {
    init(): Promise<void>;
    getGenres(): EpgGenre[];
    getChannelsByGenre(genreId: string): EpgChannel[];
    getChannel(id: string): EpgChannel | null;
    getProgramsForChannel(channelId: string): Program[];
    getCurrentProgram(channelId: string): Program | null;
    getCurrentProgramIndex(channelId: string): number;
    getInitTime(): number | null;
  };

  var WelcomeScreen: {
    init(): Promise<void>;
  };

  var FeedbackSystem: {
    showParticipantPrompt(resolve: () => void): void;
  };

  // =========================================================================
  // Third-party CDN globals
  // =========================================================================

  /** Chart.js — loaded via CDN script tag. Minimal declaration for type-checking. */
  interface ChartConstructor {
    new(ctx: CanvasRenderingContext2D | null, config: object): { destroy(): void };
  }
  var Chart: ChartConstructor;

  /** QRCode.js — loaded via CDN script tag. Minimal declaration for type-checking. */
  interface QRCodeOptions {
    text: string;
    width?: number;
    height?: number;
    colorDark?: string;
    colorLight?: string;
    correctLevel?: number;
  }
  interface QRCodeConstructor {
    new(container: Element, options: QRCodeOptions): void;
    CorrectLevel: { L: number; M: number; Q: number; H: number };
  }
  var QRCode: QRCodeConstructor;

  /** HLS.js — loaded via CDN script tag. Minimal declaration for type-checking. */
  interface HlsInstance {
    loadSource(url: string): void;
    attachMedia(media: HTMLMediaElement): void;
    on(event: string, handler: (...args: unknown[]) => void): void;
    destroy(): void;
  }
  interface HlsConstructor {
    new(): HlsInstance;
    isSupported(): boolean;
    Events: Record<string, string>;
  }
  var Hls: HlsConstructor;

  interface Window {
    trackEvent: typeof trackEvent;
    initSession: typeof initSession;
    endSession: typeof endSession;
    Analytics: typeof Analytics;
    Schemas?: Record<string, unknown>;
  }
}

export {};
